services:
  api:
    build:
      context: .
      target: build
    command: pnpm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MARIADB_USER: sigelab
      MARIADB_PASSWORD: sigelab
      MARIADB_DATABASE: sigelab
      MARIADB_ROOT_PASSWORD: sigelab
    ports:
      - "3307:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
